# Generated by Django 3.2.9 on 2022-01-13 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapi', '0002_todolist'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.CharField(max_length=64)),
                ('pressure', models.CharField(max_length=64)),
                ('humidity', models.CharField(max_length=64)),
            ],
        ),
    ]
